VERILOG = ../src/spectrum.v ../src/dpram.v ../src/keyboard.v \
	  ../src/Z80/tv80_core.v ../src/Z80/tv80n.v ../src/Z80/tv80_mcode.v \
	  ../src/Z80/tv80_reg.v ../src/Z80/tv80_alu.v \
	  ../src/osd/osd.v ../src/osd/spi_osd.v ../src/osd/spi_ram_btn.v \
	  ../src/spirw_slave_v.v \
	  ../src/video.v ../src/hdmi.v ../src/ps2.v pll.v

PIN_DEF = ulx3s_v20.lpf

include ulx3s.mk

