VERILOG = ../src/spectrum.v ../src/dpram.v ../src/keyboard.v \
	  ../src/Z80/tv80_core.v ../src/Z80/tv80n.v ../src/Z80/tv80_mcode.v \
	  ../src/Z80/tv80_reg.v ../src/Z80/tv80_alu.v \
	  ../src/osd/osd.v ../src/osd/spi_osd.v ../src/osd/spi_ram_btn.v \
	  ../src/osd/spirw_slave_v.v \
	  ../src/clk_25_125_48_6_25.v \
	  ../src/usb/usb11_phy_vhdl/usb_tx_phy.v \
	  ../src/usb/usb11_phy_vhdl/usb_rx_phy.v \
	  ../src/usb/usb11_phy_vhdl/usb_phy.v \
	  ../src/usb/usbhost/usbh_crc5.v \
	  ../src/usb/usbhost/usbh_host_hid.v \
	  ../src/usb/usbhost/usbh_sie.v \
	  ../src/usb/usbhost/usbh_crc16.v \
	  ../src/usb/report_decoder/usbh_report_decoder_darfon.v \
	  ../src/video.v ../src/hdmi.v ../src/ps2.v pll.v

PIN_DEF = ulx3s_v20.lpf

include ulx3s.mk

