VERILOG = ../src/spectrum.v ../src/dpram.v ../src/rom.v \
	  ../src/Z80/tv80_core.v ../src/Z80/tv80n.v ../src/Z80/tv80_mcode.v \
	  ../src/Z80/tv80_reg.v ../src/Z80/tv80_alu.v \
	  pll.v ../src/hdmi.v

PIN_DEF = ulx3s_v20.lpf

include ulx3s.mk

